# Generated by Django 3.2.4 on 2021-06-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatToy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
