# Generated by Django 3.2.4 on 2021-06-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_cattoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cattoys',
            field=models.ManyToManyField(to='main_app.CatToy'),
        ),
    ]
